### ISSUE TITLE
More transition effects

### ISSUE THREAD

**Issue by shaahink** [bergben/ng2-page-transition#2]
Hi, 

How is it possible to add more transition effects? Like slide for instance. 

Thanks

**Comment by bergben** [comment]
Hi, this is currently not possible. 
Solution would be: 
Add an `@Input` which animation should be executed
Add animation "slideActive" to the animations
Add animation "slideInactive" to the animations
https://github.com/bergben/ng2-page-transition/blob/master/src/ng2-page-transition.component.ts#L7

Change "Active" and "Inactive" to user selected animation by the `@Input`
https://github.com/bergben/ng2-page-transition/blob/master/src/ng2-page-transition.component.ts#L27
https://github.com/bergben/ng2-page-transition/blob/master/src/ng2-page-transition.component.ts#L32

I currently don't have time to implement this, a PR would be awesome. Otherwise I may be free in about 2 weeks to do this

**Comment by bergben** [comment]
You can add any custom transition that you wish now: https://github.com/bergben/ng2-page-transition#custom-transition
